### ISSUE TITLE
无法使用自定义壁纸

### ISSUE THREAD

**Issue by YKZG0000** [AmzGrainRain/LightSP#4]
使用自定义壁纸时会黑屏

**Comment by AmzGrainRain** [comment]
较早的版本确实存在你说的问题（抱歉哈，写代码时疏忽了），建议咱把扩展升级到最新版本 3.1.4.1，我这边实测最新的版本是没有这个问题的。如果还是有那请说明下你设置的自定义壁纸的格式（.jpg/.png/.webp等）。可以的话，按下 F12 打开控制台，如果有报错也请一并提交过来，这样我才能确定是哪里出了问题。

> 这是扩展目前的分发渠道：
>
> 微软扩展商店：https://microsoftedge.microsoft.com/addons/detail/mianbaepkeclkoclkoikhlgdfpdelnfi
> 火狐扩展商店：https://addons.mozilla.org/zh-CN/firefox/addon/lightsp-%E8%BD%BB%E8%B5%B7%E5%A7%8B%E9%A1%B5
